'''
This module has functions for making LaTeX code for various tables.
'''

param_names = [
    'CRRA',
    'DiscFac',
    'MedCurve',
    'LifeUtility',
    'MargUtilityShift',
    'Cfloor',
    'Bequest0',
    'Bequest1',
    'MedShkMean0',
    'MedShkMeanSex',
    'MedShkMeanAge',
    'MedShkMeanAgeSq',
    'MedShkMeanHealth',
    'MedShkMeanHealthSq',
    'MedShkStd0',
    'MedShkStd1',
    'HealthNext0',
    'HealthNextSex',
    'HealthNextAge',
    'HealthNextAgeSq',
    'HealthNextHealth',
    'HealthNextHealthSq',
    'HealthShkStd0',
    'HealthShkStd1',
    'HealthProd0',
    'HealthProd1',
    'HealthProd2',
    'Mortality0',
    'MortalitySex',
    'MortalityAge',
    'MortalityAgeSq',
    'MortalityHealth',
    'MortalityHealthSq'
    ]

param_tex = [
    '\\rho',
    '\\beta',
    '\\nu',
    '\\lambda',
    '\\alpha',
    '\\underline{C}',
    '\\omega_0',
    '\\omega_1',
    '\\mu_0',
    '\\mu_s',
    '\\mu_{a1}',
    '\\mu_{a2}',
    '\\mu_{h1}',
    '\\mu_{h2}',
    '\\sigma_0',
    '\\sigma_h',
    '\\gamma_0',
    '\\gamma_s',
    '\\gamma_{a1}',
    '\\gamma_{a2}',
    '\\gamma_{h1}',
    '\\gamma_{h2}',
    '\\kappa_0',
    '\\hat{\\kappa}_1',
    '\\hat{\\kappa}_2',
    '\\varsigma_0',
    '\\varsigma_h',
    '\\theta_0',
    '\\theta_s',
    '\\theta_{a1}',
    '\\theta_{a2}',
    '\\theta_{h1}',
    '\\theta_{h2}',
    ]

param_desc = [
    'Intertemporal discount factor (biennial)',
    'Coefficient of relative risk aversion',
    'Curvature of returns to mitigative care',
    'Utility level shifter: $u(\\lambda)=0$',
    'Marginal utility shifter for health',
    'Effective consumption floor (\$10,000)',
    'blah'
    ]